//! # Veil CLI
//!
//! Command-line tool for managing Veil E2E encrypted LLM inference.
//!
//! ## Commands
//!
//! - `veil keygen` — Generate a new server key pair
//! - `veil inspect-key` — Show public key info from a secret key
//! - `veil encrypt` — Encrypt a payload (for testing)
//! - `veil decrypt` — Decrypt an envelope (for testing)
//! - `veil proxy` — Start the client proxy
//! - `veil server` — Start the decryption server
//! - `veil test-roundtrip` — Test full encrypt/decrypt cycle

use anyhow::{Context, Result};
use clap::{Parser, Subcommand};

use veil_core::{
    keys::StaticKeyPair,
    session::{ClientSession, ServerSession},
};

#[derive(Parser)]
#[command(
    name = "veil",
    about = "Veil — E2E encrypted LLM inference",
    version,
    long_about = "End-to-end encryption for LLM API traffic.\n\nVeil keeps your prompts and responses confidential from all intermediaries.\nOnly you and the inference engine see plaintext."
)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Generate a new X25519 server key pair.
    Keygen {
        /// Output format: "text" or "json".
        #[arg(short, long, default_value = "text")]
        format: String,

        /// Write server config TOML to this path.
        #[arg(short, long)]
        output: Option<String>,
    },

    /// Display public key info from a base64 secret key.
    InspectKey {
        /// Base64-encoded secret key.
        #[arg(short, long)]
        secret: String,
    },

    /// Test a full encrypt → decrypt roundtrip.
    TestRoundtrip {
        /// Plaintext message to encrypt.
        #[arg(short, long, default_value = "Hello from Veil!")]
        message: String,
    },

    /// Encrypt a file or stdin (for testing/debugging).
    Encrypt {
        /// Server public key (base64).
        #[arg(short = 'k', long)]
        public_key: String,

        /// Input text to encrypt.
        #[arg(short, long)]
        input: String,
    },

    /// Start the Veil client proxy.
    Proxy {
        /// Path to client config TOML file.
        #[arg(short, long)]
        config: Option<String>,

        /// Server public key (overrides config).
        #[arg(short = 'k', long)]
        server_key: Option<String>,

        /// Upstream URL (overrides config).
        #[arg(short, long)]
        upstream: Option<String>,

        /// Listen address (overrides config).
        #[arg(short, long)]
        listen: Option<String>,
    },

    /// Start the Veil decryption server.
    Server {
        /// Path to server config TOML file.
        #[arg(short, long)]
        config: String,
    },
}

#[tokio::main]
async fn main() -> Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Commands::Keygen { format, output } => cmd_keygen(&format, output.as_deref()),
        Commands::InspectKey { secret } => cmd_inspect_key(&secret),
        Commands::TestRoundtrip { message } => cmd_test_roundtrip(&message),
        Commands::Encrypt { public_key, input } => cmd_encrypt(&public_key, &input),
        Commands::Proxy {
            config,
            server_key,
            upstream,
            listen,
        } => {
            cmd_proxy(
                config.as_deref(),
                server_key.as_deref(),
                upstream.as_deref(),
                listen.as_deref(),
            )
            .await
        }
        Commands::Server { config } => cmd_server(&config).await,
    }
}

fn cmd_keygen(format: &str, output: Option<&str>) -> Result<()> {
    let kp = StaticKeyPair::generate();

    match format {
        "json" => {
            let json = serde_json::json!({
                "secret_key": kp.secret_base64(),
                "public_key": kp.public_base64(),
                "algorithm": "X25519",
                "key_id": "default",
                "warning": "Keep secret_key secure! Never share it."
            });
            println!("{}", serde_json::to_string_pretty(&json)?);
        }
        _ => {
            println!("🔑 Veil Key Pair Generated");
            println!("═══════════════════════════════════════════════");
            println!("Secret Key: {}", kp.secret_base64());
            println!("Public Key: {}", kp.public_base64());
            println!("Algorithm:  X25519 + HKDF-SHA256 + AES-256-GCM");
            println!("═══════════════════════════════════════════════");
            println!();
            println!("⚠️  Keep the secret key secure!");
            println!("📤 Share the public key with clients.");
        }
    }

    // Write server config if output path given
    if let Some(path) = output {
        let config_toml = format!(
            r#"# Veil Server Configuration
# Generated by `veil keygen`

listen_addr = "0.0.0.0:8481"
backend_url = "http://127.0.0.1:8000"
server_secret_key = "{}"
key_id = "default"
max_body_size = 10485760
request_timeout_secs = 300
metrics_enabled = true
"#,
            kp.secret_base64()
        );

        std::fs::write(path, &config_toml)
            .with_context(|| format!("Failed to write config to {}", path))?;
        println!("\n✅ Server config written to: {}", path);
    }

    Ok(())
}

fn cmd_inspect_key(secret_b64: &str) -> Result<()> {
    let kp = StaticKeyPair::from_secret_base64(secret_b64).context("Invalid secret key")?;

    println!("🔍 Key Info");
    println!("Public Key: {}", kp.public_base64());
    println!("Algorithm:  X25519");
    Ok(())
}

fn cmd_test_roundtrip(message: &str) -> Result<()> {
    println!("🧪 Testing Veil encrypt/decrypt roundtrip...");
    println!();

    // Generate server key pair
    let server_kp = StaticKeyPair::generate();
    println!("✅ Server key pair generated");
    println!("   Public Key: {}", server_kp.public_base64());

    // Create client session
    let mut client_session = ClientSession::new(&server_kp.public_base64(), "test-key")
        .context("Failed to create client session")?;
    println!("✅ Client session created (ephemeral key exchange done)");

    // Encrypt
    let (envelope, metadata) = client_session
        .encrypt_request(message.as_bytes(), "test-model", Some(10))
        .context("Encryption failed")?;

    println!("✅ Request encrypted");
    println!("   Ciphertext size: {} bytes", envelope.payload_size());
    println!("   Model: {}", metadata.model);

    // Create server session
    let server_session = ServerSession::new(
        &server_kp,
        &metadata.ephemeral_key,
        "test-key",
        &metadata.request_id,
        &metadata.timestamp,
    )
    .context("Failed to create server session")?;
    println!("✅ Server session created");

    // Decrypt request
    let decrypted = server_session
        .decrypt_request(&envelope)
        .context("Decryption failed")?;
    let decrypted_str =
        String::from_utf8(decrypted.clone()).context("Decrypted data is not valid UTF-8")?;

    println!("✅ Request decrypted");
    println!("   Plaintext: {}", decrypted_str);

    // Encrypt response
    let response_text = format!("Response to: {}", message);
    let resp_envelope = server_session
        .encrypt_response(response_text.as_bytes())
        .context("Response encryption failed")?;
    println!("✅ Response encrypted");

    // Decrypt response
    let decrypted_resp = client_session
        .decrypt_response(&resp_envelope)
        .context("Response decryption failed")?;
    let resp_str =
        String::from_utf8(decrypted_resp).context("Decrypted response is not valid UTF-8")?;

    println!("✅ Response decrypted");
    println!("   Response: {}", resp_str);

    println!();
    assert_eq!(decrypted_str, message);
    println!("🎉 Roundtrip test PASSED — all encryption/decryption verified!");

    Ok(())
}

fn cmd_encrypt(public_key: &str, input: &str) -> Result<()> {
    let mut session = ClientSession::new(public_key, "cli").context("Failed to create session")?;

    let (envelope, metadata) = session
        .encrypt_request(input.as_bytes(), "cli", None)
        .context("Encryption failed")?;

    let json = envelope.to_json().context("Serialization failed")?;

    println!("{}", json);
    eprintln!("Ephemeral Key: {}", metadata.ephemeral_key);

    Ok(())
}

async fn cmd_proxy(
    _config_path: Option<&str>,
    server_key: Option<&str>,
    upstream: Option<&str>,
    listen: Option<&str>,
) -> Result<()> {
    let mut config = veil_client::config::ClientConfig::default();

    if let Some(key) = server_key {
        config.server_public_key = key.to_string();
    }
    if let Some(url) = upstream {
        config.upstream_url = url.to_string();
    }
    if let Some(addr) = listen {
        config.listen_addr = addr.to_string();
    }

    if config.server_public_key.is_empty() {
        anyhow::bail!("Server public key is required. Use --server-key or config file.");
    }

    veil_client::proxy::run_proxy(config).await
}

async fn cmd_server(config_path: &str) -> Result<()> {
    let config = veil_server::config::ServerConfig::from_file(config_path)
        .context("Failed to load server config")?;

    veil_server::server::run(config).await
}
